### ISSUE TITLE
Redesign Notification UX

### ISSUE THREAD

**Issue by simonwex** [mozilla/togetherjs#191]
- [x] animate notifications - https://github.com/mozilla/towtruck/issues/146
- [x] update the notification UI - https://github.com/mozilla/towtruck/issues/464 
- [x] add notification types - https://github.com/mozilla/towtruck/issues/410 
- [x] remove double window notification - https://github.com/mozilla/towtruck/issues/199
- [x] Make sure "joining" and "exiting" notifications fade away -  https://github.com/mozilla/towtruck/issues/478 
- [x] update participant same page notification - https://github.com/mozilla/towtruck/issues/369
- [x] notify user to send a new session link - https://github.com/mozilla/towtruck/issues/456 
- [x] Participant notification should go away if they leave the session - https://github.com/mozilla/towtruck/issues/487 
- [x] remove Come Back for simplicity? or you can just chat them - https://github.com/mozilla/towtruck/issues/493 

Reference:
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#participant-joins-session
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#participant-leaves-session
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#notifications
