### ISSUE TITLE
Redesign Walkthrough

### ISSUE THREAD

**Issue by aarondruck** [mozilla/togetherjs#432]
- [x] make walkthrough windows non-actionable - https://github.com/mozilla/towtruck/issues/306 
- [x] edit Walkthrough text for Creator and Participant - https://github.com/mozilla/towtruck/issues/367 
- [x] add area to point to how to End a session - https://github.com/mozilla/towtruck/issues/432 
- [x] make the "Click here to collaborate with friends" slide is clearer. click where? - https://github.com/mozilla/towtruck/issues/473 
- [ ] skip Walkthrough 2nd time through, if join another session - https://github.com/mozilla/towtruck/issues/474 
- [x] point to the Participant avatars in the walkthrough - https://github.com/mozilla/towtruck/issues/475 
- [x] enter name - https://github.com/mozilla/towtruck/issues/520

Reference:
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#walkthroughhelp
