### ISSUE TITLE
Redesign Dock

### ISSUE THREAD

**Issue by aarondruck** [mozilla/togetherjs#507]
- [x] create new icon for "hangup" - https://github.com/mozilla/towtruck/issues/477 
- [x] add tooltips for names on avatars on hover (and "This is you" when over your avatar") - https://github.com/mozilla/towtruck/issues/261 
- [x] color in Avatar border with their color- https://github.com/mozilla/towtruck/issues/77 
- [x] add different button states - https://github.com/mozilla/towtruck/issues/448 
- [x] make "Help" text instead of icon - https://github.com/mozilla/towtruck/issues/476 
- [x] add cursor and dock participant states - https://github.com/mozilla/towtruck/issues/368 
- [x] add tooltips on icons to explain what they are - https://github.com/mozilla/towtruck/issues/484 

Reference:
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#dock

![img_8015](https://f.cloud.github.com/assets/2692810/460096/69be2622-b415-11e2-8ea8-90fcc8539edf.png)
![img_8016](https://f.cloud.github.com/assets/2692810/460097/69d651a2-b415-11e2-91d8-94e68d27cf55.png)
