### ISSUE TITLE
redesign Chat window

### ISSUE THREAD

**Issue by aarondruck** [mozilla/togetherjs#509]
- [x] add permanent usernames in the Chat window - https://github.com/mozilla/towtruck/issues/431
- [x] change "Me" to your name - https://github.com/mozilla/towtruck/issues/481
- [x] name it Chatroom instead of Chat - https://github.com/mozilla/towtruck/issues/490 
- [x] add notifications inline in chat - https://github.com/mozilla/towtruck/issues/461
- [x] user should get inline notification when they have the Chat window open - https://github.com/mozilla/towtruck/issues/199 

Reference:
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#chat-2
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#behaviors-6
