### ISSUE TITLE
redesign Profile window

### ISSUE THREAD

**Issue by aarondruck** [mozilla/togetherjs#510]
The Profile window is now a part of a dropdown menu
- [x] allow user to update color - https://github.com/mozilla/towtruck/issues/363
- [x] allow user to update avatar - https://github.com/mozilla/towtruck/issues/364
- [x] create new Profile window - https://github.com/mozilla/towtruck/issues/453
- [x] remove checkbox next to name - https://github.com/mozilla/towtruck/issues/483 

Reference:
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#profile-2
