### ISSUE TITLE
redesign cursors

### ISSUE THREAD

**Issue by aarondruck** [mozilla/togetherjs#511]
- [x] color mouse pulse/click with participant color - https://github.com/mozilla/towtruck/issues/491 
- [x] animate arrows and ellipses next to cursor - https://github.com/mozilla/towtruck/issues/46  
- [x] new cursor icon - https://github.com/mozilla/towtruck/issues/436

Reference:
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#participant-finger
