### ISSUE TITLE
redesign participant experience

### ISSUE THREAD

**Issue by aarondruck** [mozilla/togetherjs#512]
- [x] create Participant windows - https://github.com/mozilla/towtruck/issues/365 
  (https://github.com/mozilla/towtruck/issues/312 done)
- [ ] create participant entering/exiting session animation - https://github.com/mozilla/towtruck/issues/227 
- [x] update Follow feature on a page - https://github.com/mozilla/towtruck/issues/463  
- [x] user should go to whatever page creator is on when they join the session - https://github.com/mozilla/towtruck/issues/488 
- [ ] create user Handshake feature - https://github.com/mozilla/towtruck/issues/372 
- [ ] create admin controls / remove participant feature - https://github.com/mozilla/towtruck/issues/366
- [x] scrollTo position of user when joining that page - https://github.com/mozilla/towtruck/issues/489 
- [ ] Clicking the participant cursor-name-box should scrollTo user and open participant window - https://github.com/mozilla/towtruck/issues/486  

Reference:
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#participants-1
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#participants-2
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#participant-finger
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#notifications
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#participant-joins-session
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#participant-leaves-session
https://github.com/mozilla/towtruck/wiki/Design-v.Beta#creator-ends-session
